// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals

#include "verilated_vcd_c.h"
#include "Vtb_systolic_array__Syms.h"


void Vtb_systolic_array___024root__trace_chg_0_sub_0(Vtb_systolic_array___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtb_systolic_array___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_systolic_array___024root__trace_chg_0\n"); );
    // Body
    Vtb_systolic_array___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtb_systolic_array___024root*>(voidSelf);
    Vtb_systolic_array__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    Vtb_systolic_array___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtb_systolic_array___024root__trace_chg_dtype____0(Vtb_systolic_array___024root* vlSelf, VerilatedVcd::Buffer* bufp, uint32_t offset, const VlUnpacked<CData/*7:0*/, 8>& __VdtypeVar);
void Vtb_systolic_array___024root__trace_chg_dtype____1(Vtb_systolic_array___024root* vlSelf, VerilatedVcd::Buffer* bufp, uint32_t offset, const VlUnpacked<CData/*7:0*/, 8>& __VdtypeVar);

void Vtb_systolic_array___024root__trace_chg_0_sub_0(Vtb_systolic_array___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_systolic_array___024root__trace_chg_0_sub_0\n"); );
    Vtb_systolic_array__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 0);
    if (VL_UNLIKELY((((vlSelfRef.__Vm_traceActivity[1U] 
                       | vlSelfRef.__Vm_traceActivity[2U]) 
                      | vlSelfRef.__Vm_traceActivity[3U])))) {
        bufp->chgCData(oldp+0,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[0U][0U]),8);
        bufp->chgCData(oldp+1,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[0U][0U]),8);
        bufp->chgCData(oldp+2,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[0U][1U]),8);
        bufp->chgCData(oldp+3,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[0U][1U]),8);
        bufp->chgCData(oldp+4,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[0U][2U]),8);
        bufp->chgCData(oldp+5,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[0U][2U]),8);
        bufp->chgCData(oldp+6,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[0U][3U]),8);
        bufp->chgCData(oldp+7,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[0U][3U]),8);
        bufp->chgCData(oldp+8,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[0U][4U]),8);
        bufp->chgCData(oldp+9,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[0U][4U]),8);
        bufp->chgCData(oldp+10,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[0U][5U]),8);
        bufp->chgCData(oldp+11,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[0U][5U]),8);
        bufp->chgCData(oldp+12,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[0U][6U]),8);
        bufp->chgCData(oldp+13,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[0U][6U]),8);
        bufp->chgCData(oldp+14,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[0U][7U]),8);
        bufp->chgCData(oldp+15,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[0U][7U]),8);
        bufp->chgCData(oldp+16,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[1U][0U]),8);
        bufp->chgCData(oldp+17,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[1U][0U]),8);
        bufp->chgCData(oldp+18,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[1U][1U]),8);
        bufp->chgCData(oldp+19,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[1U][1U]),8);
        bufp->chgCData(oldp+20,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[1U][2U]),8);
        bufp->chgCData(oldp+21,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[1U][2U]),8);
        bufp->chgCData(oldp+22,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[1U][3U]),8);
        bufp->chgCData(oldp+23,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[1U][3U]),8);
        bufp->chgCData(oldp+24,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[1U][4U]),8);
        bufp->chgCData(oldp+25,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[1U][4U]),8);
        bufp->chgCData(oldp+26,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[1U][5U]),8);
        bufp->chgCData(oldp+27,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[1U][5U]),8);
        bufp->chgCData(oldp+28,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[1U][6U]),8);
        bufp->chgCData(oldp+29,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[1U][6U]),8);
        bufp->chgCData(oldp+30,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[1U][7U]),8);
        bufp->chgCData(oldp+31,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[1U][7U]),8);
        bufp->chgCData(oldp+32,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[2U][0U]),8);
        bufp->chgCData(oldp+33,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[2U][0U]),8);
        bufp->chgCData(oldp+34,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[2U][1U]),8);
        bufp->chgCData(oldp+35,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[2U][1U]),8);
        bufp->chgCData(oldp+36,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[2U][2U]),8);
        bufp->chgCData(oldp+37,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[2U][2U]),8);
        bufp->chgCData(oldp+38,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[2U][3U]),8);
        bufp->chgCData(oldp+39,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[2U][3U]),8);
        bufp->chgCData(oldp+40,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[2U][4U]),8);
        bufp->chgCData(oldp+41,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[2U][4U]),8);
        bufp->chgCData(oldp+42,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[2U][5U]),8);
        bufp->chgCData(oldp+43,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[2U][5U]),8);
        bufp->chgCData(oldp+44,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[2U][6U]),8);
        bufp->chgCData(oldp+45,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[2U][6U]),8);
        bufp->chgCData(oldp+46,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[2U][7U]),8);
        bufp->chgCData(oldp+47,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[2U][7U]),8);
        bufp->chgCData(oldp+48,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[3U][0U]),8);
        bufp->chgCData(oldp+49,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[3U][0U]),8);
        bufp->chgCData(oldp+50,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[3U][1U]),8);
        bufp->chgCData(oldp+51,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[3U][1U]),8);
        bufp->chgCData(oldp+52,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[3U][2U]),8);
        bufp->chgCData(oldp+53,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[3U][2U]),8);
        bufp->chgCData(oldp+54,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[3U][3U]),8);
        bufp->chgCData(oldp+55,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[3U][3U]),8);
        bufp->chgCData(oldp+56,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[3U][4U]),8);
        bufp->chgCData(oldp+57,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[3U][4U]),8);
        bufp->chgCData(oldp+58,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[3U][5U]),8);
        bufp->chgCData(oldp+59,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[3U][5U]),8);
        bufp->chgCData(oldp+60,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[3U][6U]),8);
        bufp->chgCData(oldp+61,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[3U][6U]),8);
        bufp->chgCData(oldp+62,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[3U][7U]),8);
        bufp->chgCData(oldp+63,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[3U][7U]),8);
        bufp->chgCData(oldp+64,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[4U][0U]),8);
        bufp->chgCData(oldp+65,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[4U][0U]),8);
        bufp->chgCData(oldp+66,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[4U][1U]),8);
        bufp->chgCData(oldp+67,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[4U][1U]),8);
        bufp->chgCData(oldp+68,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[4U][2U]),8);
        bufp->chgCData(oldp+69,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[4U][2U]),8);
        bufp->chgCData(oldp+70,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[4U][3U]),8);
        bufp->chgCData(oldp+71,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[4U][3U]),8);
        bufp->chgCData(oldp+72,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[4U][4U]),8);
        bufp->chgCData(oldp+73,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[4U][4U]),8);
        bufp->chgCData(oldp+74,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[4U][5U]),8);
        bufp->chgCData(oldp+75,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[4U][5U]),8);
        bufp->chgCData(oldp+76,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[4U][6U]),8);
        bufp->chgCData(oldp+77,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[4U][6U]),8);
        bufp->chgCData(oldp+78,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[4U][7U]),8);
        bufp->chgCData(oldp+79,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[4U][7U]),8);
        bufp->chgCData(oldp+80,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[5U][0U]),8);
        bufp->chgCData(oldp+81,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[5U][0U]),8);
        bufp->chgCData(oldp+82,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[5U][1U]),8);
        bufp->chgCData(oldp+83,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[5U][1U]),8);
        bufp->chgCData(oldp+84,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[5U][2U]),8);
        bufp->chgCData(oldp+85,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[5U][2U]),8);
        bufp->chgCData(oldp+86,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[5U][3U]),8);
        bufp->chgCData(oldp+87,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[5U][3U]),8);
        bufp->chgCData(oldp+88,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[5U][4U]),8);
        bufp->chgCData(oldp+89,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[5U][4U]),8);
        bufp->chgCData(oldp+90,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[5U][5U]),8);
        bufp->chgCData(oldp+91,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[5U][5U]),8);
        bufp->chgCData(oldp+92,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[5U][6U]),8);
        bufp->chgCData(oldp+93,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[5U][6U]),8);
        bufp->chgCData(oldp+94,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[5U][7U]),8);
        bufp->chgCData(oldp+95,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[5U][7U]),8);
        bufp->chgCData(oldp+96,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[6U][0U]),8);
        bufp->chgCData(oldp+97,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[6U][0U]),8);
        bufp->chgCData(oldp+98,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[6U][1U]),8);
        bufp->chgCData(oldp+99,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[6U][1U]),8);
        bufp->chgCData(oldp+100,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[6U][2U]),8);
        bufp->chgCData(oldp+101,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[6U][2U]),8);
        bufp->chgCData(oldp+102,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[6U][3U]),8);
        bufp->chgCData(oldp+103,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[6U][3U]),8);
        bufp->chgCData(oldp+104,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[6U][4U]),8);
        bufp->chgCData(oldp+105,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[6U][4U]),8);
        bufp->chgCData(oldp+106,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[6U][5U]),8);
        bufp->chgCData(oldp+107,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[6U][5U]),8);
        bufp->chgCData(oldp+108,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[6U][6U]),8);
        bufp->chgCData(oldp+109,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[6U][6U]),8);
        bufp->chgCData(oldp+110,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[6U][7U]),8);
        bufp->chgCData(oldp+111,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[6U][7U]),8);
        bufp->chgCData(oldp+112,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[7U][0U]),8);
        bufp->chgCData(oldp+113,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[7U][0U]),8);
        bufp->chgCData(oldp+114,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[7U][1U]),8);
        bufp->chgCData(oldp+115,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[7U][1U]),8);
        bufp->chgCData(oldp+116,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[7U][2U]),8);
        bufp->chgCData(oldp+117,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[7U][2U]),8);
        bufp->chgCData(oldp+118,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[7U][3U]),8);
        bufp->chgCData(oldp+119,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[7U][3U]),8);
        bufp->chgCData(oldp+120,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[7U][4U]),8);
        bufp->chgCData(oldp+121,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[7U][4U]),8);
        bufp->chgCData(oldp+122,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[7U][5U]),8);
        bufp->chgCData(oldp+123,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[7U][5U]),8);
        bufp->chgCData(oldp+124,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[7U][6U]),8);
        bufp->chgCData(oldp+125,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[7U][6U]),8);
        bufp->chgCData(oldp+126,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__a_wire[7U][7U]),8);
        bufp->chgCData(oldp+127,(vlSelfRef.tb_systolic_array__DOT__dut__DOT__b_wire[7U][7U]),8);
    }
    if (VL_UNLIKELY((vlSelfRef.__Vm_traceActivity[2U]))) {
        bufp->chgCData(oldp+128,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+129,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+130,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+131,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+132,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+133,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+134,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+135,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+136,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+137,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+138,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+139,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+140,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+141,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+142,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+143,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+144,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+145,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+146,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+147,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+148,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+149,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+150,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+151,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__0__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+152,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+153,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+154,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+155,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+156,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+157,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+158,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+159,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+160,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+161,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+162,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+163,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+164,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+165,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+166,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+167,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+168,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+169,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+170,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+171,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+172,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+173,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+174,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+175,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__1__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+176,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+177,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+178,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+179,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+180,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+181,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+182,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+183,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+184,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+185,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+186,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+187,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+188,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+189,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+190,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+191,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+192,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+193,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+194,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+195,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+196,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+197,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+198,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+199,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__2__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+200,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+201,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+202,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+203,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+204,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+205,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+206,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+207,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+208,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+209,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+210,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+211,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+212,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+213,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+214,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+215,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+216,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+217,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+218,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+219,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+220,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+221,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+222,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+223,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__3__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+224,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+225,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+226,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+227,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+228,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+229,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+230,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+231,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+232,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+233,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+234,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+235,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+236,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+237,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+238,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+239,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+240,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+241,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+242,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+243,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+244,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+245,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+246,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+247,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__4__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+248,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+249,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+250,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+251,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+252,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+253,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+254,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+255,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+256,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+257,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+258,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+259,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+260,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+261,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+262,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+263,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+264,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+265,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+266,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+267,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+268,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+269,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+270,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+271,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__5__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+272,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+273,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+274,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+275,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+276,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+277,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+278,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+279,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+280,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+281,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+282,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+283,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+284,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+285,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+286,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+287,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+288,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+289,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+290,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+291,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+292,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+293,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+294,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+295,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__6__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+296,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+297,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+298,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__0__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+299,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+300,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+301,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__1__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+302,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+303,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+304,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__2__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+305,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+306,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+307,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__3__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+308,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+309,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+310,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__4__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+311,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+312,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+313,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__5__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+314,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+315,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+316,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__6__KET____DOT__pe_inst__acc),32);
        bufp->chgCData(oldp+317,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__a_out),8);
        bufp->chgCData(oldp+318,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__b_out),8);
        bufp->chgIData(oldp+319,(vlSelfRef.tb_systolic_array__DOT__dut__DOT____Vcellout__gen_row__BRA__7__KET____DOT__gen_col__BRA__7__KET____DOT__pe_inst__acc),32);
    }
    bufp->chgBit(oldp+320,(vlSelfRef.tb_systolic_array__DOT__clk));
    bufp->chgBit(oldp+321,(vlSelfRef.tb_systolic_array__DOT__rst));
    Vtb_systolic_array___024root__trace_chg_dtype____0(vlSelf, bufp, 322, vlSelfRef.tb_systolic_array__DOT__a_row);
    Vtb_systolic_array___024root__trace_chg_dtype____1(vlSelf, bufp, 330, vlSelfRef.tb_systolic_array__DOT__b_col);
    bufp->chgIData(oldp+338,(vlSelfRef.tb_systolic_array__DOT__i),32);
}

void Vtb_systolic_array___024root__trace_chg_dtype____0(Vtb_systolic_array___024root* vlSelf, VerilatedVcd::Buffer* bufp, uint32_t offset, const VlUnpacked<CData/*7:0*/, 8>& __VdtypeVar) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_systolic_array___024root__trace_chg_dtype____0\n"); );
    Vtb_systolic_array__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode +  offset);
    bufp->chgCData(oldp+0,(__VdtypeVar[0]),8);
    bufp->chgCData(oldp+1,(__VdtypeVar[1]),8);
    bufp->chgCData(oldp+2,(__VdtypeVar[2]),8);
    bufp->chgCData(oldp+3,(__VdtypeVar[3]),8);
    bufp->chgCData(oldp+4,(__VdtypeVar[4]),8);
    bufp->chgCData(oldp+5,(__VdtypeVar[5]),8);
    bufp->chgCData(oldp+6,(__VdtypeVar[6]),8);
    bufp->chgCData(oldp+7,(__VdtypeVar[7]),8);
}

void Vtb_systolic_array___024root__trace_chg_dtype____1(Vtb_systolic_array___024root* vlSelf, VerilatedVcd::Buffer* bufp, uint32_t offset, const VlUnpacked<CData/*7:0*/, 8>& __VdtypeVar) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_systolic_array___024root__trace_chg_dtype____1\n"); );
    Vtb_systolic_array__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode +  offset);
    bufp->chgCData(oldp+0,(__VdtypeVar[0]),8);
    bufp->chgCData(oldp+1,(__VdtypeVar[1]),8);
    bufp->chgCData(oldp+2,(__VdtypeVar[2]),8);
    bufp->chgCData(oldp+3,(__VdtypeVar[3]),8);
    bufp->chgCData(oldp+4,(__VdtypeVar[4]),8);
    bufp->chgCData(oldp+5,(__VdtypeVar[5]),8);
    bufp->chgCData(oldp+6,(__VdtypeVar[6]),8);
    bufp->chgCData(oldp+7,(__VdtypeVar[7]),8);
}

void Vtb_systolic_array___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_systolic_array___024root__trace_cleanup\n"); );
    // Body
    Vtb_systolic_array___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtb_systolic_array___024root*>(voidSelf);
    Vtb_systolic_array__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[3U] = 0U;
}
